version: '3.8'

services:
  student-technical-task:
    image: student-technical-task:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    environment:
      COLUMNS: 80
      LINES: 24
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
